language: node_js
node_js:
- node
cache: npm
install:
- make install_dep
script:
- make test
before_deploy:
- openssl aes-256-cbc -K $encrypted_8a47e2a0718b_key -iv $encrypted_8a47e2a0718b_iv
  -in CI/travis_to_server.enc -out CI/travis_to_server -d
- eval $(exec ssh-agent)
deploy:
- provider: script
  script: make deploy
