language: node_js
node_js:
- node
cache: npm
install:
- make install_dep
script:
- make test
before_deploy:
- openssl aes-256-cbc -K $encrypted_90c8f0f61a28_key -iv $encrypted_90c8f0f61a28_iv
  -in travis_to_server.enc -out travis_to_server -d
- eval $(exec ssh-agent)
deploy:
- provider: script
  script: make docker
